spring:
  elasticsearch:
    # ES服务以及对应的端口 该端口没有设置密码和集群单机就用9200  集群的话使用9300进行通信  集群使用多个ip使用,分割
    uris: 192.168.154.128:9200
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://192.168.154.128:3306/dog2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: 123456

server:
  port: 8080
  servlet:
    # 应用的访问路径
    context-path: /



mybatis-plus:
  # Mapper.xml 文件位置 Maven 多模块项目的扫描路径需以 classpath*: 开头
  mapperLocations: classpath*:mapper/*Mapper.xml
  #  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名 实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.example.elasticsearch.entity
  checkConfigLocation : true
  configuration: # MyBatis 原生支持的配置
    # 是否开启自动驼峰命名规则（camel case）映射
    mapUnderscoreToCamelCase: true
    jdbc-type-for-null: null
  global-config: # 全局策略配置
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-not-delete-value: 0
      logic-delete-value: 2
logging:
  level:
    com:
      example:
        elasticsearch: debug